language: node_js
node_js:
  - "8"
services:
  - docker
install: true
before_install:
- sudo apt-get install -y python-pip
- sudo pip install awscli
- if [[ "$TRAVIS_BRANCH" = "master" ]] ; then docker build --build-arg NODE_ENV=Prod -t bgs . ; fi
script:
- if [ $TRAVIS_TEST_RESULT -eq 0 ]; then BRANCH=$TRAVIS_BRANCH IMAGE=bgs COMMIT=$TRAVIS_COMMIT bin/ecs-deploy/push-and-deploy.sh; fi
