language: node_js
node_js:
  - "8"
services:
  - docker
install: true
before_install:
- sudo apt-get install -y python-pip
- sudo pip install awscli
- docker build  -t bgs .
script:
- BRANCH=$TRAVIS_BRANCH IMAGE=bgs COMMIT=$TRAVIS_COMMIT bin/ecs-deploy/push-and-deploy.sh

